#!/usr/bin/env python3
"""Generate a play's story view — the golden path walked in order with
each node's complete prompt inlined in place.

A derived rendering (Studio → Fabro plan §3): assembled from the same
sources as the workflow itself — brief.md (§4 story), workflow.fabro
(nodes, edges, scripts), prompts/*.md — so it cannot drift. Never edit
story.md by hand; re-run this.

Usage: generate-story.py <play-dir> [output-md]
"""
import re
import sys
from pathlib import Path

from workflow_model import golden_path, parse_workflow


def main(play_dir, output_path=None):
    play = Path(play_dir)
    story_path = Path(output_path) if output_path is not None else play / "story.md"
    brief = (play / "brief.md").read_text()
    wf_text = (play / "workflow.fabro").read_text()
    nodes, edges = parse_workflow(wf_text)
    order = golden_path(edges)

    story_m = re.search(r"\*\*The story\*\*(.*?)\*\*The graph\*\*", brief, re.S)
    story = story_m.group(1).strip() if story_m else "(story not found in brief §4)"
    story = re.sub(r"^\([^)]*\):?\s*", "", story)

    out = []
    out.append(f"# Story view — {play.name}")
    out.append("")
    out.append(
        "*(DERIVED RENDERING — generated by `studio/tools/generate-story.py` "
        "from brief.md §4, workflow.fabro, and prompts/. Read it to see the "
        "whole play working together as one story; never run it, never edit "
        "it — re-derive it.)*"
    )
    out.append("")
    out.append("## The story")
    out.append("")
    out.append(story)
    out.append("")
    out.append("## The golden path, move by move")
    for i, n in enumerate(order, 1):
        attrs = nodes.get(n, {})
        label = attrs.get("label", n)
        out.append("")
        out.append(f"### {i}. `{n}` — {label}")
        bounces = [
            f"`{d.get('label', d.get('condition', ''))}` → `{dst}`"
            for src, dst, d in edges
            if src == n and dst != (order[i] if i < len(order) else "exit")
        ]
        if bounces:
            out.append("")
            out.append("Routes besides the golden path: " + " · ".join(bounces))
        if "script" in attrs:
            out.append("")
            out.append("Software node — the script is the prompt:")
            out.append("")
            out.append("```sh")
            out.append(attrs["script"].replace('\\"', '"'))
            out.append("```")
        else:
            pf = attrs.get("prompt", "")
            if pf.startswith("@"):
                body = (play / pf[1:]).read_text().strip()
            else:
                # Inline prompt — non-Raven builds carry the prompt inline rather
                # than as prompts/<node>.md; render it verbatim, unescaped.
                body = pf.replace('\\"', '"').strip()
            if body:
                out.append("")
                out.append("```markdown")
                out.append(body)
                out.append("```")
    story_path.write_text("\n".join(out) + "\n")
    print(f"{story_path} written: {len(order)} moves on the golden path: {' → '.join(order)}")


if __name__ == "__main__":
    if len(sys.argv) not in (2, 3):
        print("usage: generate-story.py <play-dir> [output-md]", file=sys.stderr)
        sys.exit(2)
    main(sys.argv[1], sys.argv[2] if len(sys.argv) == 3 else None)
