/**
 * Pure parsers that lift the authored Play-page spine out of the play's
 * *derived* `story.md` (generated by `studio/tools/generate-story.py` from
 * brief §4 + workflow.fabro + prompts/). The Play page reads story.md because
 * it is reliable across plays — unlike brief.md, whose section headers vary per
 * play (the exemplar combines "§§1–3"). We render structure, never re-author it.
 *
 * story.md shape this depends on:
 *   ## The story
 *   <a human-forward narrative paragraph>
 *   ## The golden path, move by move
 *   ### 1. `locate` — Locate the thread boundary
 *   Routes besides the golden path: `Refuse` → `exit`
 *   ```markdown
 *   ---
 *   move: locate
 *   doer: judgment
 *   emits: runtime/target-spans.md — …
 *   ---
 *   …
 */

export interface PlayMove {
  /** the move's ordinal in the golden path */
  n: number;
  /** the move id, e.g. "locate" */
  id: string;
  /** the human title after the em-dash */
  title: string;
  /** "judgment" | "mechanical" | "human" | null — parenthetical notes stripped */
  doer: string | null;
  /** the off-golden-path routes line, verbatim (carries `code` + arrows), or null */
  routes: string | null;
  /** the move's first `emits:` line, verbatim, or null */
  emits: string | null;
}

const SECTION_STORY = /^##\s+The story\s*$/i;
const HEADING_2 = /^##\s+/;
const MOVE_HEAD = /^###\s+(\d+)\.\s+`([^`]+)`\s+—\s+(.+?)\s*$/;
const ROUTES_LINE = /^Routes besides the golden path:\s*(.+?)\s*$/i;
const DOER_LINE = /^doer:\s*(.+?)\s*$/i;
const EMITS_LINE = /^emits:\s*(.+?)\s*$/i;

/**
 * The "## The story" narrative paragraph — the play in plain words. Returns the
 * section body (markdown) through the next H2, or null if absent.
 */
export function parseStoryNarrative(storyText: string): string | null {
  const lines = storyText.split("\n");
  let start = -1;
  for (let i = 0; i < lines.length; i += 1) {
    if (SECTION_STORY.test(lines[i] ?? "")) {
      start = i + 1;
      break;
    }
  }
  if (start === -1) {
    return null;
  }
  const out: string[] = [];
  for (let i = start; i < lines.length; i += 1) {
    if (HEADING_2.test(lines[i] ?? "")) {
      break;
    }
    out.push(lines[i] ?? "");
  }
  const text = out.join("\n").trim();
  return text.length > 0 ? text : null;
}

/**
 * The golden-path moves, in order: id, title, doer, off-path routes, and the
 * move's emitted artifact. A move with no embedded prompt block (e.g. a
 * software-stub node) still appears, with doer/emits null.
 */
export function parseMoves(storyText: string): PlayMove[] {
  const lines = storyText.split("\n");
  const moves: PlayMove[] = [];
  let current: PlayMove | null = null;
  for (const raw of lines) {
    const line = raw ?? "";
    const head = MOVE_HEAD.exec(line);
    if (head != null) {
      if (current != null) {
        moves.push(current);
      }
      current = {
        doer: null,
        emits: null,
        id: head[2] ?? "",
        n: Number(head[1]),
        routes: null,
        title: head[3] ?? "",
      };
      continue;
    }
    if (current == null) {
      continue;
    }
    const routes = ROUTES_LINE.exec(line);
    if (routes != null && current.routes == null) {
      current.routes = routes[1] ?? null;
      continue;
    }
    const doer = DOER_LINE.exec(line);
    if (doer != null && current.doer == null) {
      // Drop a trailing parenthetical gloss: "mechanical (closed rules…)".
      current.doer = (doer[1] ?? "").replace(/\s*\(.*\)\s*$/, "").trim() || null;
      continue;
    }
    const emits = EMITS_LINE.exec(line);
    if (emits != null && current.emits == null) {
      current.emits = emits[1] ?? null;
    }
  }
  if (current != null) {
    moves.push(current);
  }
  return moves;
}

export interface PlayRoute {
  /** the route label, e.g. "Fix entries" (the branch's name) */
  label: string;
  /** the move id the branch routes to, e.g. "frame", or "exit" */
  target: string;
}

const ROUTE_ITEM = /`([^`]*)`\s*(?:→|->)\s*`([^`]+)`/g;

/**
 * Parse a move's off-golden-path routes line into structured edges. The line
 * (carried verbatim on PlayMove.routes) looks like:
 *   `Fix entries` → `frame` · `Fix hunch` → `relate`
 * Labels may be empty (a software node's unlabeled loop-back); those are kept,
 * since the target still matters. Returns [] when there are no routes.
 */
export function parseRoutes(routes: string | null): PlayRoute[] {
  if (routes == null) {
    return [];
  }
  const out: PlayRoute[] = [];
  for (const m of routes.matchAll(ROUTE_ITEM)) {
    out.push({ label: (m[1] ?? "").trim(), target: (m[2] ?? "").trim() });
  }
  return out;
}
