_version = 1

[server.api]
url = "http://127.0.0.1:3000/api/v1"

[server.web]
enabled = true
url = "http://127.0.0.1:3000"

[server.auth]
methods = ["dev-token"]

[server.integrations.github]
strategy = "app"
app_id = "3760416"
client_id = "Iv23litq9EMk1tv4PSqC"
slug = "fabro-of-alexandria"

[run.environment]
id = "default"
